version: '3.8'
services:
  web:
    build: .
    ports:
      - "5039:5039"
    environment:
      - DOCKER=yes
      - FLASK_PORT=5039
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    volumes:
      - ./app/traducciones:/app/traducciones
    restart: unless-stopped